services:
  jobdb:
    image: postgres
    volumes:
      - jobdb_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_USER: db
      POSTGRES_DB: jobdb
      POSTGRES_PASSWORD: db
    networks:
      - postgres-phpmyadmin
  reviewdb:
    image: postgres
    volumes:
      - reviewdb_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_USER: db
      POSTGRES_DB: reviewdb
      POSTGRES_PASSWORD: db
    networks:
      - postgres-phpmyadmin
  companydb:
    image: postgres
    volumes:
      - companydb_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_USER: db
      POSTGRES_DB: companydb
      POSTGRES_PASSWORD: db
    networks:
      - postgres-phpmyadmin

  pgadmin:
    depends_on:
      - companydb
      - jobdb
      - reviewdb
    image: 'docker.io/dpage/pgadmin4:latest'
    ports:
      - "8090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pascal.galle@myrmod.de"
      PGADMIN_DEFAULT_PASSWORD: "root"
    networks:
      - postgres-phpmyadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

networks:
  postgres-phpmyadmin:

volumes:
  jobdb_data:
  reviewdb_data:
  companydb_data:
  pgadmin-data:
