services:
  # Database
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_USER: db
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db
    networks:
      - postgres-phpmyadmin

  # phpmyadmin
  pgadmin:
    depends_on:
      - db
    image: 'docker.io/dpage/pgadmin4:latest'
    ports:
      - "8090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pascal.galle@myrmod.de"
      PGADMIN_DEFAULT_PASSWORD: "root"
    networks:
      - postgres-phpmyadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

networks:
  postgres-phpmyadmin:

volumes:
  db_data:
  pgadmin-data:
