spring:
  application:
    name: "jobapp"

  sql:
    init:
      mode: "always"

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:test

logging:
  level:
    org:
      springframework:
        web: DEBUG
